name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'http/cves/2022/CVE-2022-45269.yaml'
    - 'http/cves/2023/CVE-2023-29204.yaml'
    - 'http/cves/2023/CVE-2023-4220.yaml'
    - 'http/cves/2023/CVE-2023-44012.yaml'
    - 'http/cves/2023/CVE-2023-4450.yaml'
    - 'http/cves/2023/CVE-2023-48728.yaml'
    - 'http/cves/2024/CVE-2024-1512.yaml'
    - 'http/cves/2024/CVE-2024-2330.yaml'
    - 'http/cves/2024/CVE-2024-34351.yaml'
    - 'http/cves/2024/CVE-2024-3742.yaml'
    - 'http/cves/2024/CVE-2024-4257.yaml'
    - 'http/cves/2024/CVE-2024-4879.yaml'
    - 'http/cves/2024/CVE-2024-5217.yaml'
    - 'http/cves/2024/CVE-2024-6289.yaml'
    - 'http/exposed-panels/falcosidekick-panel.yaml'
    - 'http/exposed-panels/gradle/gradle-develocity-panel.yaml'
    - 'http/exposures/configs/apache-ozone-conf.yaml'
    - 'http/exposures/configs/snoop-servlet-exposure.yaml'
    - 'http/exposures/files/adcs-certificate.yaml'
    - 'http/misconfiguration/servicenow-title-injection.yaml'
    - 'http/technologies/apache/apache-ozone-detect.yaml'
    - 'http/technologies/wordpress/plugins/wp-crontrol.yaml'
    - 'http/vulnerabilities/nextjs/nextjs-middleware-cache.yaml'
    - 'http/vulnerabilities/nextjs/nextjs-rsc-cache.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    if: github.repository == 'projectdiscovery/nuclei-templates'
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
