name: ✨ WordPress Plugins - Update

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Update:
    runs-on: ubuntu-latest
    if: github.repository == 'projectdiscovery/nuclei-templates'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Install Python3
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/wordpress-plugins-update-requirements.txt

      - name: Update Templates
        id: update-templates
        run: python3 .github/scripts/wordpress-plugins-update.py

      - uses: projectdiscovery/actions/setup/git@v1

      - uses: projectdiscovery/actions/commit@v1
        with:
          files: '.'
          message: 'chore: update WordPress Plugins 🤖'

      - run: git push origin $GITHUB_REF
